description = "I make life painful for developers"

[nativeTools]
shell = { overrides = ["git commit .*", "git push .*"] }
read = { overrides = [".*Cargo.toml.*"] }
write = { overrides = [".*Cargo.toml.*"] }
aws = { disableAutoReadOnly = false }
