description = "I make life painful for developers"

[nativeTools]
shell = { allowOverride = ["git commit .*", "git push .*"] }
read = { allowOverride = [".*Cargo.toml.*"] }
write = { allowOverride = [".*Cargo.toml.*"] }
aws = { disableAutoReadOnly = false }
