description = "I make life painful for developers"

[nativeTool]
shell = { allow = ["git commit .*", "git push .*"] }
read = { allow = [".*Cargo.toml.*"] }
write = { allow = [".*Cargo.toml.*"] }
aws = { disableAutoReadOnly = false }
